export default {
  blog: ["optimizing-images-for-web"],
  projekte: [
    "admin-dashboard",
    "battleship",
    "calculator",
    "code-camp",
    "etch-a-sketch",
    "landing-page",
    "lf5-statische-website",
    "library",
    "lists.txt",
    "macro-recorder",
    "mondrian",
    "portfolio",
    "python-img-rec",
    "python-warm-ups",
    "recipes",
    "restaurant-page",
    "rock-paper-scissors",
    "sign-up-form",
    "testing-practice",
    "tic-tac-toe",
    "todo-list",
    "weather-app",
  ],
};
